### ISSUE TITLE
Issue opening/building the project

### ISSUE THREAD

**Issue by billbarni** [rhomobile/rhoconnect-push-service#1]
When I try to open the (RhoConnect Push Service for Windows Mobile/CE Environment 'rhomobile/rhoconnect-push-service') project on Visual Studio 2008 or just run the build.bat file an error is presented to me and I can't continue.

> Unbale to open project
> '...\rhoconnect-push-service-master\wm\cab\ansservice\ansservice.vddproj'.
> An error was found on line #1.

Could you help me identify the issue?

**Comment by vmusulainen** [comment]
Billbarni, pls, give me some time for investigation

**Comment by vmusulainen** [comment]
Billbarni, it seems the issue in Windows line ending CR+LF and git auto changing to LF by default. 
Try to do the following:
open rhoconnect-push-service/wm/cab/ansservice/ansservice.vddproj in Windows notepad and reformat file.  Or replace all LF with CRLF with more advanced editor.

**Comment by billbarni** [comment]
Perfect. That solved it. Sorry to bother you with such stupid error.

Thanks a LOT for your time and patience.
